### PR TITLE
Fix zip archive decompression problem.

### LINKED ISSUE #94: [BUG]: Dotnet无法正常使用
**Version**
vfox 版本：0.2.4
.net 版本：8.0.2
**OS**
Windows

**Describe the bug**
无法正常使用dotnet

**Screenshots[optional]**

**Error Message**
Error: [C:\Users\GF\.version-fox\cache\dotnet\v-8.0.2\dotnet-8.0.2\host\fxr] does not exist

**个人猜想**
感觉就是路径错误，正常情况下是没有那个host文件夹的在Windows系统上

### PR DESCRIPTION
**Pull request by ahai-code**
fix #94

### CODE REVIEW

File: internal/util/decompressor.go [hunk 1]
```diff
@@ -179,21 +180,60 @@ type ZipDecompressor struct {
...
+	if err != nil {
+		return ""
+	}
+	defer r.Close()
+
+	// Stores the first element of the path of all files
+	var firstElements []string
+
+	// Checks if the slice contains the specified element
+	contains := func(slice []string, element string) bool {
```
Comment (aooohan) [inline internal/util/decompressor.go:209]: We can use `map` to replace this algorithm that the time complexity is a bit high

Comment (ahai-code) [reply internal/util/decompressor.go]: Okay, I've optimized the function

File: internal/util/decompressor.go [hunk 2]
```diff
@@ -179,21 +180,46 @@ type ZipDecompressor struct {
 }
 
 func (z *ZipDecompressor) Decompress(dest string) error {
+	rootFolderInZip := FindRootFolderInZip(z.src)
```
Comment (XuZheCheung) [inline internal/util/decompressor.go:183]:
``` suggestion:
rootFolderInZip := FindRootFolderInZip(z.src)
```

File: internal/util/decompressor.go [hunk 3]
```diff
@@ -179,21 +180,46 @@ type ZipDecompressor struct {
...
+		err := z.processZipFile(f, dest, rootFolderInZip)
 		if err != nil {
 			return err
 		}
 	}
 	return nil
 }
 
-func (z *ZipDecompressor) processZipFile(f *zip.File, dest string) error {
+func FindRootFolderInZip(zipFilePath string) string {
```
Comment (XuZheCheung) [inline internal/util/decompressor.go:198]:
``` suggestion:
func findRootFolderInZip(zipFilePath string) string{
```

**Review by XuZheCheung — CHANGES_REQUESTED** [review]

File: internal/util/decompressor.go (hunk 2 above)
Comment (aooohan) [inline internal/util/decompressor.go:183]:
```suggestion
	rootFolderInZip := findRootFolderInZip(z.src)
```

File: internal/util/decompressor.go (hunk 3 above)
Comment (aooohan) [inline internal/util/decompressor.go:198]:
```suggestion
func findRootFolderInZip(zipFilePath string) string {
```

**Review by aooohan — CHANGES_REQUESTED** [review]
